#!/bin/sh

if [ "$#" -lt 2 ] ; then
        echo "Usage: $0 <IP address> <program> [<arguments> ...]"
        exit 0
fi

I_USR_LIB=/usr/local/lib
I_USR_BIN=/usr/local/bin

# export RUNFROMIPTCPUDP_VERB=2
# 0 = syslog nothing
# 1 = syslog err/warn - default / the one you want.
# 2 = syslog info
# 3 = syslog xtra
# 4 = syslog dbg

#export RUNFROMIPTCPUDP_ADDRESS=127.0.0.2

# use -1 to not change port
# OR: Don't specify.
#export RUNFROMIPTCPUDP_PORT=900
unset  RUNFROMIPTCPUDP_PORT

export RUNFROMIPTCPUDP_PORT

export RUNFROMIPTCPUDP_ADDR="$1"

export RUNFROMIPTCPUDP_SO="${I_USR_LIB}/runfromiptcpudp.so"

export LD_PRELOAD="${LD_PRELOAD}:${RUNFROMIPTCPUDP_SO}"

# echo RUNFROMIPTCPUDP_VERB is \'$RUNFROMIPTCPUDP_VERB\'
# echo RUNFROMIPTCPUDP_PORT is \'$RUNFROMIPTCPUDP_PORT\'
# echo RUNFROMIPTCPUDP_ADDR is \'$RUNFROMIPTCPUDP_ADDR\'
# echo LD_PRELOAD is \'$LD_PRELOAD\'

if [ ! -f "$RUNFROMIPTCPUDP_SO" ] ; then
        echo "${RUNFROMIPTCPUDP_SO} not found! Exiting."
        exit 1
fi

shift

exec "$@"
